//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fileshare_utility
{
    using System;
    using System.Collections.Generic;
    
    public partial class computer
    {
        public computer()
        {
            this.mappings = new HashSet<mapping>();
        }
    
        public long computerID { get; set; }
        public string hostname { get; set; }
    
        public virtual ICollection<mapping> mappings { get; set; }
    }
}
