//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fileshare_utility
{
    using System;
    using System.Collections.Generic;
    
    public partial class mapping
    {
        public long shareID { get; set; }
        public long computerID { get; set; }
        public long userID { get; set; }
        public string letter { get; set; }
        public string username { get; set; }
        public string date { get; set; }
    
        public virtual computer computer { get; set; }
        public virtual user user { get; set; }
        public virtual share share { get; set; }
    }
}
