//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fileshare_utility
{
    using System;
    using System.Collections.Generic;
    
    public partial class server
    {
        public server()
        {
            this.shares = new HashSet<share>();
        }
    
        public long serverID { get; set; }
        public string hostname { get; set; }
        public bool active { get; set; }
        public string domain { get; set; }
        public string date { get; set; }
    
        public virtual ICollection<share> shares { get; set; }
    }
}
