//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fileshare_utility
{
    using System;
    using System.Collections.Generic;
    
    public partial class share
    {
        public share()
        {
            this.mappings = new HashSet<mapping>();
        }
    
        public long shareID { get; set; }
        public long serverID { get; set; }
        public string shareName { get; set; }
        public bool active { get; set; }
    
        public virtual ICollection<mapping> mappings { get; set; }
        public virtual server server { get; set; }
    }
}
